version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: | 
            sudo su -
            docker build -t nodejswebapp -t rockwang415/nodejswebapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u rockwang666@163.com --password-stdin
            docker push rockwang415/nodejswebapp1:latest
workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image


  
