version: 2.1
jobs:
  build_test:
    machine: true
    resource_class: rockwangselfrunner/demo  
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
  build_docker_image:
    machine: true
    resource_class: rockwangselfrunner/demo  
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: | 
            docker build -t nodejswebapp -t rockwang415/nodejswebapp1:latest
            echo $DOCKER_PASSWORD | docker login -u rockwang666@163.com --password-stdin
            docker push rockwang415/nodejswebapp1:latest
workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image


  
